---
- name: Install dnsmasq
  apt:
    name:
      - dnsmasq
  tags:
    - pxe

- name: configure dnsmasq base (DHCP, TFTP)
  template:
    src: templates/dnsmasq-base.conf.j2
    dest: /etc/dnsmasq.d/base.conf
  notify: restart dnsmasq
  tags:
    - pxe

- name: enable Raspberry Pi Boot
  copy:
    src: files/rpi.conf
    dest: /etc/dnsmasq.d/
  notify: restart dnsmasq

- name: create dnsmasq.d pib.conf
  template:
    src: templates/pibs.conf.j2
    dest: /etc/dnsmasq.d/pibs.conf
  notify: restart dnsmasq
  tags:
    - pibs

- name: create dnsmasq.d switch.conf
  template:
    src: templates/switch.conf.j2
    dest: /etc/dnsmasq.d/switch.conf
  notify: restart dnsmasq

- name: configure UEFI PXE test clients
  include_tasks: test_clients.yml
  when: pxe_test_clients is defined
  tags:
    - pxe-test
