---
- name: apt update/upgrade
  apt:
    # name: "*"
    upgrade: true
    state: latest
    update_cache: true
    cache_valid_time: 86400

- name: install gst packages
  apt:
    name:
      - jq
      - gstreamer1.0-tools
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-plugins-base-apps
      - gstreamer1.0-libcamera
        # - libcamera0
      - rpicam-apps-lite
        # - rpicam-apps
      - lm-sensors
# Tenkawa: this combination seems to work   rpicam-apps  libcamera-ipa libcamera0.3 gstreamer1.0-libcamera
  tags:
    - streaming

# Camera scripts and systemd service are in the fpgas-online-cam deb.
# The deb's postinstall runs systemctl daemon-reload.
- name: Install fpgas-online-cam
  ansible.builtin.apt:
    name: fpgas-online-cam
    state: present
  tags:
    - cam

- name: enable cam.service
  systemd:
    name: fpgas-cam.service
    enabled: yes
  tags:
    cam
