---
- name: Arty_wire
  ansible.builtin.copy:
    src: "files/is_wire/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: u+x
  with_items:
    - arty_wire.sh
  tags:
    - ia

- name: Install systemd arty_wire service
  ansible.builtin.copy:
    src: files/is_wire/arty_wire.service
    dest: /etc/systemd/system/arty_wire.service
  notify: Reload-systemd
  tags:
    - ia

- name: Enable arty_wire.service
  ansible.builtin.systemd:
    name: arty_wire.service
    enabled: true
  failed_when: false
  tags:
    - ia
