---
- name: Arty_blink
  ansible.builtin.copy:
    src: "files/arty_blink/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: u+x
  with_items:
    - arty_blink.sh
  tags:
    - ab

- name: Install systemd arty_blink service
  ansible.builtin.copy:
    src: files/arty_blink/arty_blink.service
    dest: /etc/systemd/system/arty_blink.service
  notify: Reload-systemd
  tags:
    - ab

- name: Enable arty_blink.service
  ansible.builtin.systemd:
    name: arty_blink.service
    enabled: true
  failed_when: false
  tags:
    - ab
