- name: systemd pistat_ssh.service
  template:
    src: "files/{{ item }}.service"
    dest: "/etc/systemd/system/{{ item }}.service"
  notify: reload-systemd
  with_items:
    - pistat_ssh
    - pistat_cam
    - pistat_info
    - pistat_shutdown
  tags:
    - pistat

- name: enable pistat services
  systemd:
    name: "{{ item }}"
    enabled: true
  failed_when: false
  with_items:
    - pistat_ssh
    - pistat_cam
    - pistat_info
    - pistat_shutdown
  tags:
    - pistat
