- name: Tftpd port systemd
  lineinfile:
    path: /usr/lib/systemd/system/atftpd.socket
    regexp: "ListenDatagram=69"
    line: "ListenDatagram={{ tftpd_port }}"
  notify: Reload-systemd
  tags:
    - tftpd

- name: Tftpd port conf
  replace:
    path: /etc/default/atftpd
    regexp: "--port 69"
    replace: "--port {{ tftpd_port }}"
  tags:
    - tftpd

- name: Pi tftp dir user writable
  ansible.builtin.file:
    dest: /srv/tftp
    owner: "pi"
    mode: "u+w"
    state: directory
  tags:
    - tftpd
