---
- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: Restart wssh
  systemd:
    name: wssh.socket
    state: restarted

- name: Reload systemd
  systemd:
    daemon_reload: true
