---
- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded

- name: Restart wssh
  ansible.builtin.systemd:
    name: wssh.socket
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
