---
- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: Restart django services
  systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - gunicorn
    - daphne
    - uvicorn
