---
- name: Install scripts to manage pi states
  ansible.builtin.copy:
    src: "scripts/{{ item }}"
    dest: "/usr/local/sbin/{{ item }}"
    mode: preserve
  with_items:
    - maintenance.sh
    - production.sh
    - chroot-mount-pi-fs.bash
  tags:
    - manage
    - qemu

- name: Put the pi boot system into maintenance mode
  ansible.builtin.command: maintenance.sh
  when: false
