---
- name: Restart network-manager
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted

- name: Restart networking
  ansible.builtin.systemd:
    name: networking
    state: restarted

- name: Restart dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq
    state: restarted

- name: Restart chrony
  ansible.builtin.systemd:
    name: chrony
    state: restarted
