---
- name: Restart network-manager
  systemd:
    name: NetworkManager
    state: restarted

- name: Restart networking
  systemd:
    name: networking
    state: restarted

- name: Restart dnsmasq
  systemd:
    name: dnsmasq
    state: restarted

- name: Restart chrony
  systemd:
    name: chrony
    state: restarted
