---
- name: Verify server roles (nbp)
  hosts: nbp
  become: true
  tasks:
    - name: verify firewall
      include_role:
        name: firewall
        tasks_from: verify/main.yml
      tags: [verify, firewall]

    - name: verify nfs
      include_role:
        name: nfs
        tasks_from: verify/main.yml
      tags: [verify, nfs]

    - name: verify img
      include_role:
        name: img
        tasks_from: verify/main.yml
      tags: [verify, img]

    - name: verify fixpi
      include_role:
        name: fixpi
        tasks_from: verify/main.yml
      tags: [verify, fixpi]

    - name: verify pxe
      include_role:
        name: pxe
        tasks_from: verify/main.yml
      tags: [verify, pxe]

- name: Verify uhubctl
  hosts: uhubctl
  become: true
  tasks:
    - name: verify uhubctl
      include_role:
        name: uhubctl
        tasks_from: verify/main.yml
      tags: [verify, uhubctl]

- name: Verify web roles (pig)
  hosts: pig
  become: true
  tasks:
    - name: verify site
      include_role:
        name: site
        tasks_from: verify/main.yml
      tags: [verify, site]

    - name: verify wssh
      include_role:
        name: wssh
        tasks_from: verify/main.yml
      tags: [verify, wssh]

    - name: verify cam/stream-server
      include_role:
        name: cam/stream-server
        tasks_from: verify/main.yml
      tags: [verify, cam-stream]

- name: Verify Pi roles
  hosts: pi
  become: true
  tasks:
    - name: verify Pi netboot
      include_role:
        name: fixpi
        tasks_from: verify/pi.yml
      tags: [verify, pi-netboot]
