---
- name: restart dnsmasq
  systemd:
    name: dnsmasq
    # state: restarted

- name: reload nginx
  systemd:
    name: nginx
    state: restarted

- name: restart django services
  systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - gunicorn
    - daphne
    - uvicorn
