---
- name: restart dnsmasq
  systemd:
    name: dnsmasq
    # state: restarted

- name: reload nginx
  systemd:
    name: nginx
    state: restarted

- name: restart gunicorn
  systemd:
    name: gunicorn
    state: restarted

- name: restart daphne
  systemd:
    name: daphne
    state: restarted

- name: restart uvicorn
  systemd:
    name: uvicorn
    state: restarted
