---
- name: Restart dnsmasq
  systemd:
    name: dnsmasq
    # state: restarted

- name: Reload nginx
  systemd:
    name: nginx
    state: restarted

- name: Restart django services
  systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - gunicorn
    - daphne
    - uvicorn

- name: Restart fleet-consumer
  systemd:
    name: fleet-consumer
    state: restarted
  when: fleet_broker | default(false)

- name: Reload systemd
  systemd:
    daemon_reload: true
